apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.cac.io
spec:
  group: cac.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                repository:
                  type: string
                project:
                  type: string
  scope: Cluster
  names:
    plural: images
    singular: image
    kind: Image
